import type { Metadata } from 'next';
import { Toaster } from '@/components/ui/sonner';
import './globals.css';

import Header from './components/header/Header';
import Footer from './components/footer/footer';
import ProviderWrapper from './providerWrapper';
import ErrorWrapper from './errorWrapper';
import I18nProviderWrapper from './i18nextProvider';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ProviderWrapper>
      <I18nProviderWrapper>
        <html lang="en">
          <head>
            <link rel="icon" href="/api.png" />
          </head>
          <body>
            <ErrorWrapper>
              <Header />
              {children}
              <Toaster />
              <Footer />
            </ErrorWrapper>
          </body>
        </html>
      </I18nProviderWrapper>

    </ProviderWrapper>
  );
}
