import type { Metadata } from 'next';
import './globals.css';

import Header from './ui/components/header/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/api.png" />
      </head>
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
